server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/coding_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ram123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.secret=MyVerySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong!
jwt.expiration=86400000
cors.allowed-origins=http://localhost:3000
# ??? Email (Gmail SMTP) ???????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rs0688699@gmail.com
spring.mail.password=rffv pwfu atks dxhe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
abstract.api.key=3f04c141d6ab46a18f9a0f451c8275df
onlinecompiler.api.key=73ff6f3a526d1903ceb7ca73271f0779
onlinecompiler.api.url=https://api.onlinecompiler.io/api/run-code-sync/
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions